name: Wails Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wails Build
        uses: The-Egg-Corp/wails-build-action@v1.4
        with:
          build: true
          build-platform: windows/amd64
          wails-version: v2.10.1
          go-version: 1.21
          node-version: 18
          
      - name: Confirm Executable Output
        run: |
          dir build\bin
          if (!(Test-Path "build\bin\superglide-overlay.exe")) {
            throw "Executable not found!"
          }

      - name: Zip Source Code
        run: |
          git archive -o source.zip HEAD

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            build/bin/superglide-overlay.exe
            source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
