name: Wails Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wails Build
        uses: The-Egg-Corp/wails-build-action@v1.4
        with:
          build: true
          build-platform: windows/amd64
          wails-version: v2.10.1
          go-version: 1.21
          node-version: 18

      - name: Zip Source Code
        run: Compress-Archive -Path * -DestinationPath source.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            build/bin/*.exe
            source.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            build/bin/*.exe
            source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
